#pragma once

enum OverworldNPCSprites
{
	EVENT_OBJ_GFX_RED_NORMAL, //0
	EVENT_OBJ_GFX_RED_BIKE, //1
	EVENT_OBJ_GFX_RED_SURFING,  //2
	EVENT_OBJ_GFX_RED_FIELD_MOVE, //3
	EVENT_OBJ_GFX_RED_FISHING, //4
	EVENT_OBJ_GFX_RED_VS_SEEKER, //5
	EVENT_OBJ_GFX_RED_BIKE_VS_SEEKER, //6
	EVENT_OBJ_GFX_LEAF_NORMAL, //7
	EVENT_OBJ_GFX_LEAF_BIKE, //8
	EVENT_OBJ_GFX_LEAF_SURFING, //9
	EVENT_OBJ_GFX_LEAF_FIELD_MOVE, //10
	EVENT_OBJ_GFX_LEAF_FISHING, //11
	EVENT_OBJ_GFX_LEAF_VS_SEEKER, //12
	EVENT_OBJ_GFX_LEAF_BIKE_VS_SEEKER, //13
	EVENT_OBJ_GFX_BRENDAN, //14
	EVENT_OBJ_GFX_MAY, //15
	EVENT_OBJ_GFX_LITTLE_BOY, //16
	EVENT_OBJ_GFX_LITTLE_GIRL, //17
	EVENT_OBJ_GFX_YOUNGSTER, //18
	EVENT_OBJ_GFX_BOY, //19
	EVENT_OBJ_GFX_BUG_CATCHER, //20
	EVENT_OBJ_GFX_SITTING_BOY, //21
	EVENT_OBJ_GFX_LASS, //22
	EVENT_OBJ_GFX_WOMAN_1, //23
	EVENT_OBJ_GFX_BATTLE_GIRL, //24
	EVENT_OBJ_GFX_MAN, //25
	EVENT_OBJ_GFX_GUITARIST, //26
	EVENT_OBJ_GFX_FAT_GUY, //27
	EVENT_OBJ_GFX_RANDOM_WOMAN, //28
	EVENT_OBJ_GFX_BEAUTY, //29
	EVENT_OBJ_GFX_MIDDLE_AGED_MAN, //30
	EVENT_OBJ_GFX_MIDDLE_AGED_WOMAN, //31
	EVENT_OBJ_GFX_OLD_MAN, //32
	EVENT_OBJ_GFX_OLD_MAN_2, //33
	EVENT_OBJ_GFX_OLD_MAN_SLEEPING, //34
	EVENT_OBJ_GFX_OLD_WOMAN, //35
	EVENT_OBJ_GFX_SWIMMING_TUBER_M, //36
	EVENT_OBJ_GFX_TUBER_F, //37
	EVENT_OBJ_GFX_TUBER_M, //38
	EVENT_OBJ_GFX_CAMPER, //39
	EVENT_OBJ_GFX_PICNICKER, //40
	EVENT_OBJ_GFX_COOLTRAINER_M, //41
	EVENT_OBJ_GFX_COOLTRAINER_F, //42
	EVENT_OBJ_GFX_SWIMMER_M, //43
	EVENT_OBJ_GFX_SWIMMER_F, //44
	EVENT_OBJ_GFX_STANDING_SWIMMER_M, //45
	EVENT_OBJ_GFX_STANDING_SWIMMER_F, //46
	EVENT_OBJ_GFX_WORKER_M, //47
	EVENT_OBJ_GFX_WORKER_F, //48
	EVENT_OBJ_GFX_ROCKET_GRUNT_M, //49
	EVENT_OBJ_GFX_ROCKET_GRUNT_F, //50
	EVENT_OBJ_GFX_LINK_BOY, //51
	EVENT_OBJ_GFX_SUPER_NERD, //52
	EVENT_OBJ_GFX_BIKER_BALL, //53
	EVENT_OBJ_GFX_BLACK_BELT, //54
	EVENT_OBJ_GFX_SCIENTIST_MALE, //55
	EVENT_OBJ_GFX_HIKER, //56
	EVENT_OBJ_GFX_FISHERMAN, //57
	EVENT_OBJ_GFX_CHANELLER, //58
	EVENT_OBJ_GFX_CHEF, //59
	EVENT_OBJ_GFX_POLICEMAN, //60
	EVENT_OBJ_GFX_GENTLEMAN, //61
	EVENT_OBJ_GFX_SAILOR, //62
	EVENT_OBJ_GFX_SHIP_CAPTAIN, //63
	EVENT_OBJ_GFX_NURSE_JOY, //64
	EVENT_OBJ_GFX_MEDIC_FEMALE, //65
	EVENT_OBJ_GFX_NURSE_TEALA, //66
	EVENT_OBJ_GFX_MALE_RECEPTIONIST, //67
	EVENT_OBJ_GFX_MART_CLERK, //68
	EVENT_OBJ_GFX_DELIVERYMAN, //69
	EVENT_OBJ_GFX_TRAINER_TOWER_OWNER, //70
	EVENT_OBJ_GFX_OAK, //71
	EVENT_OBJ_GFX_RIVAL, //72
	EVENT_OBJ_GFX_BILL, //73
	EVENT_OBJ_GFX_LANCE, //74
	EVENT_OBJ_GFX_AGATHA, //75
	EVENT_OBJ_GFX_DAISY, //76
	EVENT_OBJ_GFX_LORELEI, //77
	EVENT_OBJ_GFX_MR_FUJI, //78
	EVENT_OBJ_GFX_BRUNO, //79
	EVENT_OBJ_GFX_BROCK, //80
	EVENT_OBJ_GFX_MISTY, //81
	EVENT_OBJ_GFX_LT_SURGE, //82
	EVENT_OBJ_GFX_ERIKA, //83
	EVENT_OBJ_GFX_KOGA, //84
	EVENT_OBJ_GFX_SABRINA, //85
	EVENT_OBJ_GFX_BLAINE, //86
	EVENT_OBJ_GFX_GIOVANNI, //87
	EVENT_OBJ_GFX_MOM, //88
};

#define EVENT_OBJ_GFX_CELIO 89
#define EVENT_OBJ_GFX_TEACHY_TV_HOST 90
#define EVENT_OBJ_GFX_GYM_GUY 91
#define EVENT_OBJ_GFX_ITEM_BALL 92
#define EVENT_OBJ_GFX_TOWN_MAP 93
#define EVENT_OBJ_GFX_POKEDEX 94

#define EVENT_OBJ_GFX_CUT_TREE 95
#define EVENT_OBJ_GFX_ROCK_SMASH_ROCK 96
#define EVENT_OBJ_GFX_PUSHABLE_BOULDER 97


#define EVENT_OBJ_GFX_FOSSIL 98
#define EVENT_OBJ_GFX_RUBY 99
#define EVENT_OBJ_GFX_SAPPHIRE 100
#define EVENT_OBJ_GFX_OLD_AMBER 101
#define EVENT_OBJ_GFX_GYM_SIGN 102
#define EVENT_OBJ_GFX_SIGN 103
#define EVENT_OBJ_GFX_TRAINER_TIPS 104
#define EVENT_OBJ_GFX_CLIPBOARD 105
#define EVENT_OBJ_GFX_METEORITE 106
#define EVENT_OBJ_GFX_LAPRAS_DOLL 107
#define EVENT_OBJ_GFX_SEAGALLOP 108
#define EVENT_OBJ_GFX_SNORLAX 109
#define EVENT_OBJ_GFX_SPEAROW 110
#define EVENT_OBJ_GFX_CUBONE 111
#define EVENT_OBJ_GFX_POLIWRATH 112
#define EVENT_OBJ_GFX_CLEFAIRY 113
#define EVENT_OBJ_GFX_PIDGEOT 114
#define EVENT_OBJ_GFX_JIGGLYPUFF 115
#define EVENT_OBJ_GFX_PIDGEY 116
#define EVENT_OBJ_GFX_CHANSEY 117
#define EVENT_OBJ_GFX_OMANYTE 118
#define EVENT_OBJ_GFX_KANGASKHAN 119
#define EVENT_OBJ_GFX_PIKACHU 120
#define EVENT_OBJ_GFX_PSYDUCK 121
#define EVENT_OBJ_GFX_NIDORAN_F 122
#define EVENT_OBJ_GFX_NIDORAN_M 123
#define EVENT_OBJ_GFX_NIDORINO 124
#define EVENT_OBJ_GFX_MEOWTH 125
#define EVENT_OBJ_GFX_SEEL 126
#define EVENT_OBJ_GFX_VOLTORB 127
#define EVENT_OBJ_GFX_SLOWPOKE 128
#define EVENT_OBJ_GFX_SLOWBRO 129
#define EVENT_OBJ_GFX_MACHOP 130
#define EVENT_OBJ_GFX_WIGGLYTUFF 131
#define EVENT_OBJ_GFX_DODUO 132
#define EVENT_OBJ_GFX_FEAROW 133
#define EVENT_OBJ_GFX_MACHOKE 134
#define EVENT_OBJ_GFX_LAPRAS 135
#define EVENT_OBJ_GFX_ZAPDOS 136
#define EVENT_OBJ_GFX_MOLTRES 137
#define EVENT_OBJ_GFX_ARTICUNO 138
#define EVENT_OBJ_GFX_MEWTWO 139
#define EVENT_OBJ_GFX_MEW 140
#define EVENT_OBJ_GFX_ENTEI 141
#define EVENT_OBJ_GFX_SUICUNE 142
#define EVENT_OBJ_GFX_RAIKOU 143
#define EVENT_OBJ_GFX_LUGIA 144
#define EVENT_OBJ_GFX_HO_OH 145
#define EVENT_OBJ_GFX_CELEBI 146
#define EVENT_OBJ_GFX_KABUTO 147
#define EVENT_OBJ_GFX_DEOXYS_D 148
#define EVENT_OBJ_GFX_DEOXYS_A 149
#define EVENT_OBJ_GFX_DEOXYS_N 150
#define EVENT_OBJ_GFX_SS_ANNE 151

//#define EVENT_OBJ_GFX_RED_UNDERWATER 256
//#define EVENT_OBJ_GFX_LEAF_UNDERWATER 257

//#define EVENT_OBJ_GFX_RED_UNDERWATER 6 //By default VS. Seeker on bike b\c not used by anything else
//#define EVENT_OBJ_GFX_LEAF_UNDERWATER 13

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define EVENT_OBJ_GFX_VAR_0 240
#define EVENT_OBJ_GFX_VAR_1 241
#define EVENT_OBJ_GFX_VAR_2 242
#define EVENT_OBJ_GFX_VAR_3 243
#define EVENT_OBJ_GFX_VAR_4 244
#define EVENT_OBJ_GFX_VAR_5 245
#define EVENT_OBJ_GFX_VAR_6 246
#define EVENT_OBJ_GFX_VAR_7 247
#define EVENT_OBJ_GFX_VAR_8 248
#define EVENT_OBJ_GFX_VAR_9 249
#define EVENT_OBJ_GFX_VAR_A 250
#define EVENT_OBJ_GFX_VAR_B 251
#define EVENT_OBJ_GFX_VAR_C 252
#define EVENT_OBJ_GFX_VAR_D 253
#define EVENT_OBJ_GFX_VAR_E 254
#define EVENT_OBJ_GFX_VAR_F 255

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define EVENT_OBJ_ID_PLAYER 0xFF
#define EVENT_OBJ_ID_CAMERA 0x7F

#ifdef UNBOUND //For Pokemon Unbound

#define EVENT_OBJ_GFX_JAX 14
#define EVENT_OBJ_GFX_LOR_GRUNT_M 15
#define EVENT_OBJ_GFX_BABY_CARRIAGE 21
#define EVENT_OBJ_GFX_NINJA_BOY 36
#define EVENT_OBJ_GFX_ACE_TRAINER_M 41
#define EVENT_OBJ_GFX_ACE_TRAINER_F 42
#define EVENT_OBJ_GFX_SKIER_M 45
#define EVENT_OBJ_GFX_SKIER_F 46
#define EVENT_OBJ_GFX_SHADOW_GRUNT_M 49
#define EVENT_OBJ_GFX_SHADOW_GRUNT_F 50
#define EVENT_OBJ_GFX_SNOW_CAMPER 51
#define EVENT_OBJ_GFX_ROUGHNECK 53
#define EVENT_OBJ_GFX_MEDIUM 58
#define EVENT_OBJ_GFX_MART_CLERK_M 68
#define EVENT_OBJ_GFX_SCIENTIST_F 70
#define EVENT_OBJ_GFX_LOG 71
#define EVENT_OBJ_GFX_RIVAL 72
#define EVENT_OBJ_GFX_LOOKER 73
#define EVENT_OBJ_GFX_MIRSKLE 74
#define EVENT_OBJ_GFX_MOLEMAN 75
#define EVENT_OBJ_GFX_MELONY 76
#define EVENT_OBJ_GFX_ELIAS 77
#define EVENT_OBJ_GFX_ARTHUR 78
#define EVENT_OBJ_GFX_MAXIMA 79
#define EVENT_OBJ_GFX_BIG_MO 80
#define EVENT_OBJ_GFX_ALICE 81
#define EVENT_OBJ_GFX_GALAVAN 82
#define EVENT_OBJ_GFX_MEL 83
#define EVENT_OBJ_GFX_VEGA 84
#define EVENT_OBJ_GFX_TESSY 85
#define EVENT_OBJ_GFX_BENJAMIN 86
#define EVENT_OBJ_GFX_GIOVANNI 87
#define EVENT_OBJ_GFX_MOM 88
#define EVENT_OBJ_GFX_ZEPH 89
#define EVENT_OBJ_GFX_AKLOVE 90
#define EVENT_OBJ_GFX_GYM_GUIDE 91
#define EVENT_OBJ_GFX_HOOPA_CONFINED 122
#define EVENT_OBJ_GFX_ZAPDOS 136
#define EVENT_OBJ_GFX_MOLTRES 137

enum
{
	EVENT_OBJ_GFX_BIRD_KEEPER = 152,
	EVENT_OBJ_GFX_BIKER,
	EVENT_OBJ_GFX_EXPERT_F,
	EVENT_OBJ_GFX_EXPERT_M,
	EVENT_OBJ_GFX_KINDLER,
	EVENT_OBJ_GFX_PAINTER,
	EVENT_OBJ_GFX_POKE_MANIAC,
	EVENT_OBJ_GFX_RANGER_F,
	EVENT_OBJ_GFX_RANGER_M,
	EVENT_OBJ_GFX_RUIN_MANIAC,
	EVENT_OBJ_GFX_DRAGON_TAMER,
	EVENT_OBJ_GFX_SCHOOL_BOY,
	EVENT_OBJ_GFX_CUE_BALL,
	EVENT_OBJ_GFX_MARLON,
	EVENT_OBJ_GFX_IVORY,
	EVENT_OBJ_GFX_WORKER,
	EVENT_OBJ_GFX_BUG_MANIAC,
	EVENT_OBJ_GFX_INTERVIEWER,
	EVENT_OBJ_GFX_CAMERAMAN,
	EVENT_OBJ_GFX_COLLECTOR,
	EVENT_OBJ_GFX_PSYCHIC_M,
	EVENT_OBJ_GFX_SNOW_GIRL,
	EVENT_OBJ_GFX_PRIMAL_GROUDON,
	EVENT_OBJ_GFX_YOUNG_MARLON,
	EVENT_OBJ_GFX_YOUNG_IVORY,
	EVENT_OBJ_GFX_AROS,
	EVENT_OBJ_GFX_SCIENTIST_SHADOW_M,
	EVENT_OBJ_GFX_SCIENTIST_SHADOW_F,
	EVENT_OBJ_GFX_SHADOW_WARRIOR,
	EVENT_OBJ_GFX_ABRA,
	EVENT_OBJ_GFX_CHARMELEON,
	EVENT_OBJ_GFX_FLOETTE_O,
	EVENT_OBJ_GFX_FLOETTE_B,
	EVENT_OBJ_GFX_FLOETTE_R,
	EVENT_OBJ_GFX_GIRATINA_O,
	EVENT_OBJ_GFX_KECLEON,
	EVENT_OBJ_GFX_INVISIBLE_PLAYER,
	EVENT_OBJ_GFX_SHOCKER,
	EVENT_OBJ_GFX_BREEDER_M,
	EVENT_OBJ_GFX_BREEDER_F,
	EVENT_OBJ_GFX_GAMBLER,
	EVENT_OBJ_GFX_IDOL,
	EVENT_OBJ_GFX_JUGGLER,
	EVENT_OBJ_GFX_JOGGER,
	EVENT_OBJ_GFX_CYCLIST_M,
	EVENT_OBJ_GFX_CYCLIST_F,
	EVENT_OBJ_GFX_RANCHER_M,
	EVENT_OBJ_GFX_RANCHER_F,
	EVENT_OBJ_GFX_RICH_MAN,
	EVENT_OBJ_GFX_RICH_WOMAN,
	EVENT_OBJ_GFX_RICH_BOY,
	EVENT_OBJ_GFX_RICH_GIRL,
	EVENT_OBJ_GFX_KOOKY_OLD_MAN,
	EVENT_OBJ_GFX_KOOKY_OLD_WOMAN,
	EVENT_OBJ_GFX_WAITER,
	EVENT_OBJ_GFX_WAITRESS,
	EVENT_OBJ_GFX_SKELI,
	EVENT_OBJ_GFX_GOLCHE,
	EVENT_OBJ_GFX_MAID,
	EVENT_OBJ_GFX_POKEFAN_M,
	EVENT_OBJ_GFX_POKE_KID,
	EVENT_OBJ_GFX_SAGE,
	EVENT_OBJ_GFX_ELDER,
	EVENT_OBJ_GFX_SOCIALITE,
	EVENT_OBJ_GFX_ATTENDANT_F,
	EVENT_OBJ_GFX_PALMER,
	EVENT_OBJ_GFX_BURGLAR,
	EVENT_OBJ_GFX_CLOWN,
	EVENT_OBJ_GFX_PARASOL_LADY,
	EVENT_OBJ_GFX_TAMER,
	EVENT_OBJ_GFX_VIDEO_GAME_KID,
	EVENT_OBJ_GFX_MART_CLERK_F,
	EVENT_OBJ_GFX_CYNTHIA,
	EVENT_OBJ_GFX_GAIL,
	EVENT_OBJ_GFX_CANDICE,
	EVENT_OBJ_GFX_PAT,
	EVENT_OBJ_GFX_PABLO,
	EVENT_OBJ_GFX_PAULA,
	EVENT_OBJ_GFX_CATHERINE,
	EVENT_OBJ_GFX_GINGER,
	EVENT_OBJ_GFX_ABIMBOLA,
	EVENT_OBJ_GFX_MAHINA,
	EVENT_OBJ_GFX_ALFORD,
	EVENT_OBJ_GFX_LIXDEL,
	EVENT_OBJ_GFX_ARABELLA = 245,
	EVENT_OBJ_GFX_PENNY,
	EVENT_OBJ_GFX_RED = 250,
};

#define EVENT_OBJ_GFX_PSYCHIC_F EVENT_OBJ_GFX_PSYCHIC_M
#define EVENT_OBJ_GFX_PORYGON 512
#define EVENT_OBJ_GFX_ID_TYRANITAR 523
#define EVENT_OBJ_GFX_ID_METAGROSS 529
#define EVENT_OBJ_GFX_ID_GARCHOMP 540
#define EVENT_OBJ_GFX_RIVAL_SURF 642
#define EVENT_OBJ_GFX_MARLON_ARM 661
#define EVENT_OBJ_GFX_MARLON_POST_GAME 662

#define EVENT_OBJ_GFX_RED_UNDERWATER 256
#define EVENT_OBJ_GFX_LEAF_UNDERWATER 256

#define EVENT_OBJ_GFX_RED_PLAYER 388
#define EVENT_OBJ_GFX_LEAF_PLAYER 396
#define EVENT_OBJ_GFX_MARLON_PLAYER 404
#define EVENT_OBJ_GFX_IVORY_PLAYER 412
#define EVENT_OBJ_GFX_ETHAN_PLAYER 420
#define EVENT_OBJ_GFX_LYRA_PLAYER 428
#define EVENT_OBJ_GFX_LUCAS_PLAYER 436
#define EVENT_OBJ_GFX_DAWN_PLAYER 444
#define EVENT_OBJ_GFX_SHADOW_GRUNT_PLAYER_M 452
#define EVENT_OBJ_GFX_SHADOW_GRUNT_PLAYER_F 460
#define EVENT_OBJ_GFX_LOR_GRUNT_PLAYER 468
#define EVENT_OBJ_GFX_PLAYER_CHAMPION_M 476
#define EVENT_OBJ_GFX_PLAYER_CHAMPION_F 484

#endif
